version: '3'

services:
  tftp-server:
    build:
      context: tftp
      dockerfile: Dockerfile
    ports:
      - "69:69/udp"
    volumes:
      - ./files/tftp:/app/tftp:ro
    restart: unless-stopped
  api-server:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8888:8888/tcp"
    volumes:
      - ./files/api:/app/api/files
      - ./files/tftp:/app/api/tftp
    restart: unless-stopped
